### PR TITLE
Prioritized Experience Replay

### PR DESCRIPTION
**Pull request by jakegrigsby**
An implementation of [Prioritized Experience Replay](https://arxiv.org/abs/1511.05952?context=cs), Schaul et al., 2016.

Key features/changes:

dqn.py: Adds logic to determine if the memory is Prioritized, and adjusts the algorithm accordingly. I've run a few tests and things seem to be working, but I'd appreciate some help looking over the math.

memory.py: Adds PrioritizedMemory, which samples experiences proportional to their TD error. Uses similar conventions to SequentialMemory.

util.py: Adds segment tree data structure used by PrioritizedMemory, which is taken almost directly from the [OpenAI baseline version](https://github.com/openai/baselines/blob/master/baselines/common/segment_tree.py).

dqn_atari.py: Modifies the dqn example to include PrioritizedMemory (Sequential is still there but commented out). Also changes the keras model to the functional api, as well as updates the Convolution2D syntax (no more deprecation warnings).

docs/dqn.md: Adds the PER paper to the references.

I've done a handful of 8 million + time step training runs as tests (on Breakout v0 and v4). Learning went smoothly. Unfortunately, there was a bug that prevented the memory's beta value from annealing properly, so I can't say for sure that it's working. That's been fixed and I'm starting a new 10 mil run. As of 2.6m everything is still going well so I think this is good enough to put up for review; I'll comment the results when it's complete.

### CODE REVIEW

**Comment by jakegrigsby** [comment]
Here is the learning curve. Not long enough to compare with any published results, but it look's like it's on pace.

breakout_v4_reward_curve

And a video, let me know if the link doesn't work:
https://drive.google.com/open?id=1Drc8nx2_nVxch1Tga27sZR1yxydzwdEa

**Comment by RaphaelMeudec** [comment]
Code is clean and it seems working very fine, thank you for this ! :tada:

**Comment by ulrikborjesson** [comment]
It seems as if the indexes are incorrect when sampling from prioritized replay when the memory is full. The sum trees don't use ring buffers and the indexes obtained from these when sampling refer to a specific index in the _value array of the sum trees. The observations and other ringbuffers on the other hand will change the mappings of indexes when full. E.g. accessing observations[0] when the memory is full won't necessarily give you an observation from index 0 in the ringbuffers data array.  The effect of this is that all priorities will refer to incorrect experiences when the memory is full. 

For example, Instead of doing: `terminal0 = self.terminals[idx - 2]`
you could access the observations and other ringbuffer storage from the data arrays. E.g.: `terminal0 = self.terminals.data[idx - 2]`

I'm not entirely sure if this might cause other bugs but the current implementation is incorrect. I have also compared this to the open ai baselines implementation and these implementations differ since the storage is just a normal list and not a ringbuffer in the baselines implementation. In other words they avoid this issue by accessing the array "directly ".

**Comment by jakegrigsby** [comment]
I’ll fix that. Thanks

**Comment by jakegrigsby** [comment]
I think this can be fixed by removing the start idx from the __getitem__ of the ring buffer:
```
def __getitem__(self, idx):
        """Return element of buffer at specific index
        # Argument
            idx (int): Index wanted
        # Returns
            The element of buffer at given index
        """
        if idx < 0 or idx >= self.length:
            raise KeyError()
        return self.data[(idx) % self.maxlen]
```
This way the items are overwriten like a normal ring buffer but are accessed by fixed idxs.

Here's the output of a rough test.
Before:
```
Priority sum tree of size 5:
1.0
1.0
1.0
1.0
1.0
Observation in index 0:
[ 0.02417545 -0.01240123 -0.02854802 -0.0528461 ]
Added 2 new observations
Updating observation in index 0 with higher priority
Observation in index 0:
[ 0.02758979 -0.01157058 -0.03669289 -0.0711951 ]
Priority of this observation:
20.91279105182547
Updating again
Priority sum tree of size 5:
832.5532074018735
1.0
1.0
1.0
1.0
```

Like you pointed out the observation in that index is changing but its priority isn't shifting with it.

After:
```
Priority sum tree of size 5:
1.0
1.0
1.0
1.0
1.0
Observation in index 0:
[ 0.02735838 -0.2061478  -0.0381168   0.20968898]
Added 2 new observations
Updating observation in index 0 with higher priority
Observation in index 0:
[ 0.02735838 -0.2061478  -0.0381168   0.20968898]
Priority of this observation:
20.91279105182547
Updating again
Priority sum tree of size 5:
832.5532074018735
1.0
1.0
1.0
1.0
```

Now both seem to be coupled together. That obs is overwritten with a recalculated priority once the memory cycles back around, but remains fixed in the meantime.

Shorter training run results:
figure_1

Looks good, but it was working before so that doesn't say much. I checked to make sure SequentialMemory still works... it shouldn't matter whether we're sampling randomly from a moving starting point or randomly from the beginning of the array. This will be included in next PR.

**Comment by ulrikborjesson** [comment]
I see one problem with that approach. Ringbuffer is a utility that might be used by users of keras-rl in their own custom implementations and by changing its behaviour you could break their implementations. I would either just access the data directly as previously suggested in the prioritized sample method or use a custom ringbuffer instead of overwriting the existing one with changes since there's nothing wrong with its behaviour in general.

**Comment by jakegrigsby** [comment]
That's the plan. I've been working on dqfd and it uses its own ring buffer that already has this change. PER will be switched to use that version without pre-loaded data.

**Comment by AloshkaD** [comment]
@jakegrigsby I don't see the prioritized memory replay implementation in memory.py. has this not been updated? I have implemented a sequential memory approach and I can implement a PMR and test. DO you mind sharing your final class/method ?

**Comment by jakegrigsby** [comment]
@AloshkaD I think it was moved into the next version release, not the master branch. There is a bug as was discussed above, which was fixed in #214. That still hasn't been merged (it got really big) and probably has some conflicts by now - I'm pretty sure the underlying memory buffers have been rewritten. I'll have some time in the next few weeks to update it and try to get everything into the next release.

**Comment by AloshkaD** [comment]
@jakegrigsby  thanks Jake!

**Comment by AloshkaD** [comment]
@jakegrigsby sorry to get back to this. I saw your implementation of PER on your keras-rl repo and I implemented it like this 
```memory = PrioritizedMemory(limit=1000000, alpha=.4,
                              start_beta=.6, end_beta=.6, window_length=WINDOW_LENGTH)```
It seemed to work in the beginning but after some episodes it troughs this error  
``` assert len(experiences) == self.batch_size``` which comes from the backward method in dgn.py
I did print the length comparison which was like this
```len(experiences)= 34
self.batch_size = 32```
Any hint on what may have been causing this is appreciated.

**Comment by jakegrigsby** [comment]
@AloshkaD that's weird. I've been testing it off and on over the past few months and haven't run into that problem. Make sure you're using the `n-step-dqn` branch if you're using my fork. If you're just using mine as a reference and adding to this one, my guess is it's an issue with the underlying memory buffer. My PER uses `PartitionedMemoryBuffer`, because it holds indices static, letting the priorities for each obs be stored in the same idx as the image.

I'll be able to work on this starting early next week. If you're still having issues hopefully I can recreate it and find the fix.

**Comment by AloshkaD** [comment]
Let me know when you start working on this and I'll work with you to fix it. 
as to using 
``` n-step-dqn``` are you referring to the policy?  

Here is my implementation anyway. 

```policy = LinearAnnealedPolicy(EpsGreedyQPolicy(), attr='eps', value_max=1., value_min=.1, value_test=0.0,nb_steps=50002)```
```dqn = DQNAgent(model=model,processor=processor, nb_actions=nb_actions, memory=memory, nb_steps_warmup=300, 
               enable_double_dqn=True, 
               enable_dueling_network=True, dueling_type='avg', 
               target_model_update=1e-2, policy=policy, gamma=.99)

dqn.compile(Adam(lr=0.00025), metrics=['mae'])```

**Comment by jakegrigsby** [comment]
@AloshkaD I meant the branch of my repo (`git checkout n-step-dqn`). That should work (hopefully).

I think #276 will get the changes into the next release. Feel free to take a look and make changes - I'd appreciate the help.

**Comment by TianLin0509** [comment]
@jakegrigsby  Excuse me, where can I find the PrioritizedMemory? I didin't find it in the memory.py

**Comment by jakegrigsby** [comment]
@TianLin0509 it's in the branch for the next release, not the master. My bug fixed never got merged though.

**Pull request merged**
