### PR TITLE
Fix Travis builds and specify an upper bound for Keras version

### PR DESCRIPTION
**Pull request by iamhectorotero**
keras-rl is no longer compatible with versions of Keras over 2.1.3 (as shown in #171). So before the necessary changes are merged, the master version should specify an upper bound for the version of Keras.

### CODE REVIEW

**Comment by iamhectorotero** [comment]
Builds for the master branch were not working. I looked into it and found that:

- Jobs using Theano were failing due to the version of gym being used.
- Jobs using Tensorflow were failing because of the way Conda installs scipy. (https://github.com/keras-team/keras-contrib/issues/211)

**Comment by iamhectorotero** [comment]
@RaphaelMeudec if you include also an upper bound for gym the builds will _finally_ pass 😊

**Comment by RaphaelMeudec** [comment]
I've seen this, I'm just thinking about cleaning a bit the script (eg add requirements, stuff like that). I'll probably merge your PR by the end of the day! Thanks for taking some time on this!

**Comment by RaphaelMeudec** [comment]
Just released a [new version](https://github.com/keras-rl/keras-rl/pull/179) which supports Keras v2.1.5 and Gym 0.10.3. I'm closing this PR. Thanks for pointing the issues !

**Pull request closed without merging**
